
name: MDCC MQTT to HA (Deep-Debug)
version: 0.4.0
slug: mdcc-mqtt-to-ha-deepdebug
description: MQTT â†’ Device/Entity Generator with Device Registry, Auto Categorization, TLS and Deep-Debug logging
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
host_network: false
options:
  mqtt_server: "mqtt://broker.example.com"
  mqtt_port: 8883
  mqtt_user: "user"
  mqtt_password: "pass"
  mqtt_topic: "physec/iotree-magdeburg-city-com/iot-platform/#"
  tls_enabled: true
  tls_insecure: false
  ca_cert: ""
  client_cert: ""
  client_key: ""
  debug: true
  on_log_verbose: true
schema:
  mqtt_server: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
  tls_enabled: bool
  tls_insecure: bool
  ca_cert: str?
  client_cert: str?
  client_key: str?
  debug: bool
  on_log_verbose: bool
