name: MDCC MQTT to HA
version: 0.2.3
slug: mdcc-mqtt-to-ha
description: Enhanced MQTT → Device → Entity generator with device registry & auto categorization
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
host_network: false
options:
  mqtt_server: "mqtt://example.com"
  mqtt_port: 1883
  mqtt_user: "user"
  mqtt_password: "pass"
  mqtt_topic: "physec/iotree-magdeburg-city-com/iot-platform/#"
schema:
  mqtt_server: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
